Hospital.Server/Controllers/ClinicalTrialsController.cs
namespace Hospital.Server.Controllers
{
    using System.Web.Mvc;
    using Data.Repository;
    using Services.Contracts;

    public class ClinicalTrialsController : BaseController
    {
        private ITrialService trialService;

        public ClinicalTrialsController(IUnitOfWork data, ITrialService trialService) : base(data)
        {
            this.trialService = trialService;
        }

        public ActionResult AllTrials()
        {
            return View(trialService.GetTrials());
        }

        public ActionResult GetClinicalTrialById(int id)
        {
            return View(trialService.GetTrialByID(id));
        }
    }
}

Hospital.Server/Controllers/HomeController.cs
namespace Hospital.Server.Controllers
{
    using Data.Repository;
    using System.Web.Mvc;
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using Models;
    using Services.Contracts;

    public class HomeController : BaseController
    {
        IHomeService homeService;

        public HomeController(IUnitOfWork data, IHomeService homeService) : base(data)
        {
            this.homeService = homeService;
        }

        public ActionResult Index()
        {
            return View(this.homeService.GetSpecialities());
        }
    }
}

Hospital.Server/Controllers/SpecialitiesController.cs
namespace Hospital.Server.Controllers
{
    using Data.Repository;
    using System.Web.Mvc;
    using Services.Contracts;

    public class SpecialitiesController : BaseController
    {
        private ISpecialitiesService specialitiesService;

        public SpecialitiesController(IUnitOfWork data, ISpecialitiesService specialitiesService) : base(data)
        {
            this.specialitiesService = specialitiesService;
        }

        public ActionResult GetSpecialityById(int id)
        {
            return View(specialitiesService.GetById(id));
        }
    }
}

Hospital.Server/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hospital.Server/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hospital.Server/Views/Home/Index.cshtml
@model List<Hospital.Server.Models.SpecialitiesIndexViewModel>


<div class="user-dashboard">
    @*<h1></h1>*@
    <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12 gutter">
            <div class="sales">
                <h2>Specialties</h2>
                <div class="btn-group">
                    <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span>Select:</span> Category
                    </button>
                    <div class="dropdown-menu">
                        @foreach (var speciality in Model)
                        {
                            <a href="@Url.Action("GetSpecialityById", "Specialities", new { id = @speciality.Id})">@speciality.Title</a>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7 col-sm-7 col-xs-12 gutter">
            <div class="sales report">
                <h2>Clinical Trials</h2>
                <div class="btn-group">
                    <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Trials
                    </button>
                    <div class="dropdown-menu">
                        @foreach (var trials in Model)
                        {
                            foreach (var trial in trials.ClinicalTrials)
                            {
                                <a href="@Url.Action("GetClinicalTrialById", "ClinicalTrials", new { id = @trial.Id})">@trial.Title</a>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>