Hospital.Server/Controllers/ClinicalResultsController.cs
namespace Hospital.Server.Controllers
{
    using Data.Repository;
    using System.Web.Mvc;
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using Models;
    using DatabaseModels;
    using Data.Constants;

    [Authorize]
    public class ClinicalResultsController : BaseController
    {

        public ClinicalResultsController(IUnitOfWork data): base(data)
        {
        }

        public ActionResult GetClinicalResult()
        {
            var result = Data.ClinicalResults
                .All()
                .Where(x => x.Patient.Id == this.UserProfile.Id)
                .OrderByDescending(x => x.AddedOn)
                .Project()
                .To<PatientResultViewModel>()
                .ToList();

            return View(result);
        }
        
        public ActionResult DownloadResult(int id)
        {
            var clinicalResult = this.Data.ClinicalResults.GetById(id);
            if (clinicalResult.File != null)
            {
                PDF file = clinicalResult.File;

                return File(file.Content, "text/plain", file.FileName);
            }
            else
            {
                PDF file = new PDF()
                {
                    Path = PathConstants.PathPDF,
                    FileName = "AsiaBecheva.pdf"
                };

                return File(file.Path + file.FileName, "text/plain");
            }
        }
    }
}

Hospital.Server/Views/ClinicalResults/GetClinicalResult.cshtml
@model List<Hospital.Server.Models.PatientResultViewModel>
@using Hospital.DatabaseModels

<header>
    <h1 style="text-align: center;">Get your Clinical Result</h1>
</header>
<section>
    <div class="container">
            @foreach (var result in Model)
            {
                if (result.StatusResult == StatusResult.Ready)
                {
                    <div class="row" style="margin:10px">
                        <span>
                            <strong>Result ID: </strong><span>@result.Id</span>
                        </span>
                        <span>
                            <strong>Status: </strong><span>@result.StatusResult</span>
                        </span>
                        <span>
                            <strong>Added on: </strong><span>@result.AddedOn</span>
                        </span>
                        <a href="@Url.Action("DownloadResult", "ClinicalResults", new { id = result.Id })" class="btn btn-success">Download file</a>
                    </div>
                }
                else
                {
                    
                    <div class="row" style="margin:10px">
                        <span>
                            <strong>Result ID: </strong><span>@result.Id  </span>
                        </span>
                        <span>
                            <strong>Status: </strong><span>@result.StatusResult</span>
                        </span>
                    </div>
                }
            }
    </div>
</section>