Hospital.Server/Controllers/AdministrationController.cs
namespace Hospital.Server.Controllers
{
    using Data.Constants;
    using Data.Repository;
    using System.Web.Mvc;
    using Models.AdminViewModels;
    using DatabaseModels;
    using Services.Contracts;
    using Services;
    using AutoMapper;

    [Authorize(Roles = GlobalConstants.adminRoleName)]
    public class AdministrationController : BaseController
    {

        private IAdminService adminService;
        private IDoctorService doctorService;
        private ITrialService trialService;

        public AdministrationController(IUnitOfWork data, IAdminService adminService, IDoctorService doctorService,
            ITrialService trialService) : base(data)
        {
            this.adminService = adminService;
            this.doctorService = doctorService;
            this.trialService = trialService;
        }


        public ActionResult ClinicalResults()
        {
            return View(this.adminService.GetAllResults());
        }

        public ActionResult Patients()
        {
            return View(this.adminService.GetPatients());
        }

        [HttpGet]
        public ActionResult AddResult(string id)
        {
            var result = new AddResultViewModel()
            {
                Patient = this.Data.Users.GetById(id)
            };

            return View(result);
        }

        [HttpPost]
        public ActionResult AddResult(AddResultViewModel result)
        {
            if (ModelState.IsValid)
            {
                var patient = this.Data.Users.GetById(result.PatientId);

                var clinRes = new ClinicalResult()
                {
                    StatusResult = result.StatusResult,
                    File = this.adminService.GetPDF(result),
                };

                patient.ClinicalResults.Add(clinRes);

                this.Data.SaveChanges();

                return RedirectToAction("Patients");
            }

            return View(result);
        }


        public ActionResult Delete(int id)
        {
            var result = this.Data.ClinicalResults.GetById(id);

            if (result != null)
            {
                this.Data.ClinicalResults.Delete(result);
                this.Data.SaveChanges();

                return RedirectToAction("ClinicalResults");
            }
            else
            {
                return this.HttpNotFound("There is no Clinical result with such ID!");
            }
        }


        public ActionResult AllDoctors()
        {
            return View(this.doctorService.GetDoctors());
        }


        public ActionResult GetDoctorById(int id)
        {
            var doctor = this.doctorService.GetById(id);

            if (doctor != null)
            {
                return View(doctor);
            }

            return HttpNotFound("There is no doctor with such ID!");
        }

        [HttpGet]
        public ActionResult AddDoctor()
        {
            var model = new AddDoctorViewModel()
            {
                Specialty = adminService.GetSpecialty()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddDoctor(AddDoctorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var specialty = this.Data.Specialities.GetById(model.SpecialityId);
                var doc = Mapper.Map<Doctor>(model);
                doc.Image = this.adminService.GetImage(model);
                doc.Specialty = specialty;
                this.Data.Doctors.Add(doc);
                this.Data.SaveChanges();

                return RedirectToAction("AllDoctors");
            }

            return View(model);
        }

        
        public ActionResult DeleteDoctor(int id)
        {
            var doc = this.Data.Doctors.GetById(id);

            if (doc == null)
            {
                return HttpNotFound("There is no doctor with such Id");
            }

            this.Data.Doctors.Delete(doc);
            this.Data.SaveChanges();
            return RedirectToAction("AllDoctors");
        }


        public ActionResult AllTrials()
        {
            return View(trialService.GetTrials());
        }

        [HttpGet]
        public ActionResult AddTrial()
        {
            AddTrialViewModel model = new AddTrialViewModel()
            {
                Specialty = this.adminService.GetSpecialty()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddTrial(AddTrialViewModel model)
        {
            if (ModelState.IsValid)
            {
                var specialty = this.Data.Specialities.GetById(model.SpecialityId);
                var trial = Mapper.Map<ClinicalTrial>(model);
                trial.Speciality = specialty;
                this.Data.ClinicalTrials.Add(trial);
                this.Data.SaveChanges();

                return RedirectToAction("AllTrials");
            }

            model.Specialty = this.adminService.GetSpecialty();

            return View(model);
        }



        public ActionResult DeleteTrial(int id)
        {
            var trial = this.Data.ClinicalTrials.GetById(id);

            if (trial == null)
            {
                return HttpNotFound("There is no trial with such Id");
            }

            this.Data.ClinicalTrials.Delete(trial);
            this.Data.SaveChanges();
            return RedirectToAction("AllTrials");
        }
    }
}

Hospital.Server/Controllers/ClinicalTrialsController.cs
namespace Hospital.Server.Controllers
{
    using System.Web.Mvc;
    using Data.Repository;
    using Services.Contracts;

    public class ClinicalTrialsController : BaseController
    {
        private ITrialService trialService;

        public ClinicalTrialsController(IUnitOfWork data, ITrialService trialService) : base(data)
        {
            this.trialService = trialService;
        }

        public ActionResult AllTrials()
        {
            return View(trialService.GetTrials());
        }

        public ActionResult GetClinicalTrialById(int id)
        {
            return View(trialService.GetTrialByID(id));
        }
    }
}

Hospital.Server/Controllers/DoctorsController.cs
namespace Hospital.Server.Controllers
{
    using System.Web.Mvc;
    using Data.Repository;
    using Services;
    using System.Web;

    public class DoctorsController : BaseController
    {
        private IDoctorService doctorService;

        public DoctorsController(IUnitOfWork data, IDoctorService doctorService) : base(data)
        {
            this.doctorService = doctorService;
        }

        public ActionResult AllDoctors()
        {
            return View(this.doctorService.GetDoctors());
        }

        public ActionResult GetDoctorById(int id)
        {
            var doctor = this.doctorService.GetById(id);

            if (doctor != null)
            {
                return View(doctor);
            }

            return HttpNotFound("There is no doctor with such ID!");
        }

        public ActionResult Image(int id)
        {
            var img = this.Data.Images.GetById(id);

            if (img == null)
            {
                throw new HttpException("Image not found");
            }

            return File(img.Content, "image/jpg");
        }
    }
}

Hospital.Server/Views/Shared/_AdministrationLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content2/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="home">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 main-menu">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("ClinicalResults", "Administration")"><i class="fa fa-file-pdf-o"></i>Clinical Results</a></li>
                        <li><a href="@Url.Action("AllTrials", "Administration")"><i class="fa fa-plus-square"></i>Trials</a></li>
                        <li><a href="@Url.Action("AllDoctors", "Administration")"><i class="fa fa-user-md"></i>Doctors</a></li>
                    </ul>
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()

                            <ul>
                                <li style="margin-top:15px;margin-right:20px;list-style-type:none;"><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </div>
    </nav>
    @RenderBody()
    
    @Scripts.Render("~/bundles/custom")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
</body>
</html>

Hospital.Server/Views/Shared/_Layout.cshtml
@using Hospital.Data.Constants

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="home">

    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="logo">
                    <a hef="home.html">
                        <img src="~/Content/images/logo2.jpg" alt="merkery_logo" class="hidden-xs hidden-sm">
                        <img src="images/circle-logo.png" alt="merkery_logo" class="visible-xs visible-sm circle-logo">
                    </a>
                </div>
                <div class="navi">
                    <ul>
                        @if (Request.IsAuthenticated && User.IsInRole(GlobalConstants.adminRoleName))
                        {
                            <li style="background-color:midnightblue"><a href="@Url.Action("ClinicalResults", "Administration")"><i class="fa fa-users" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Administration</span></a></li>
                        }
                        <li class="active"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        @if (Request.IsAuthenticated)
                        {
                            <li><a href="@Url.Action("GetClinicalResult", "ClinicalResults")"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Clinical Results</span></a></li>
                        }
                        else
                        {
                            <li><a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Clinical Results</span></a></li>
                        }
                        <li><a href="@Url.Action("AllTrials", "ClinicalTrials")"><i class="fa fa-stethoscope" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Clinical Trials</span></a></li>
                        <li><a href="@Url.Action("AllDoctors", "Doctors")"><i class="fa fa-user-md" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Doctors</span></a></li>
                        @*<li><a href="#"><i class="fa fa-info-circle" aria-hidden="true"></i><span class="hidden-xs hidden-sm">About Us</span></a></li>*@
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>
                            <div class="search hidden-xs hidden-sm">
                                <input type="text" placeholder="Search" id="search">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside" style="margin-top:12px;">
                                <ul class="list-inline header-top pull-right">
                                    <li><a href="#" class="add-project" data-toggle="modal" data-target="#add_project">Contact Us</a></li>
                                    @Html.Partial("_LoginPartial")
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>

                <div class="container body-content">
                    @RenderBody()
                    <hr />
                </div>
            </div>
        </div>
    </div>

    <div id="add_project" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header login-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title text-center">Contact us</h4>
                </div>
                <div class="modal-body">
                    <input type="text" placeholder="Name" name="Name">
                    <input type="text" placeholder="Email" name="Email">
                    <input type="text" placeholder="Age" name="Age">
                    <textarea placeholder="Message"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="cancel" data-dismiss="modal">Close</button>
                    <button type="button" class="add-project" data-dismiss="modal">Send</button>
                </div>
            </div>
        </div>
    </div>
    <footer id="footer" class="clearfix">
        <div id="footer-widgets">
            <div class="container">
                <div id="footer-wrapper">
                    <div class="row">
                        <div class="col-sm-6 col-md-3">
                            <div id="meta-3" class="widget widgetFooter widget_meta">
                                <h4 class="widgettitle">Importent Page :</h4>
                                <ul>
                                    <li><a href="#"><i class="fa fa-home fa-fw"></i> Home</a></li>
                                    <li><a href="#"><i class="fa fa-link"></i>   Privacy Policy</a></li>
                                    <li><a href="#"><i class="fa fa-envelope fa-fw"></i> Contact Us</a></li>
                                </ul>
                            </div>
                        </div> <!-- end widget1 -->
                        <div class="col-sm-6 col-md-3">
                            <div id="recent-posts-3" class="widget widgetFooter widget_recent_entries">
                                <h4 class="widgettitle">Our social media :</h4>
                                <ul>
                                    <li>
                                        <a href="https://www.facebook.com/asq.becheva" target="_blank"><i class="fa fa-facebook"></i> Facebook</a>
                                    </li>
                                    <li>
                                        <a href="https://github.com/AsiaBecheva" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>
                                    </li>
                                    <li>
                                        <a href="https://github.com/AsiaBecheva" target="_blank"><i class="fa fa-youtube"></i> Youtube</a>
                                    </li>
                                </ul>
                            </div>
                        </div> <!-- end widget1 -->
                        <div class="col-sm-6 col-md-6">
                            <div id="meta-4" class="widget widgetFooter widget_meta">
                                <h4 class="widgettitle">Subscribe :</h4>
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon">E-mail :</span>
                                        <input class="form-control" placeholder="Write your email .." type="text">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon">Phone  :</span>
                                        <input class="form-control" placeholder="+000000" type="text">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="button">Subscribe !</button>
                                        </span>
                                    </div>
                                </div>

                            </div>
                        </div> 
                    </div> 
                </div> 
            </div> 
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('[data-toggle="offcanvas"]').click(function () {
                $("#navigation").toggleClass("hidden-xs");
            });
        });
    </script>
    
</body>
</html>